- name: Add vault agent config
  become: 'yes'
  become_method: sudo
  template:
    src: "{{ vault_config_template_file }}"
    dest: /opt/vault/agent/vault-agent.hcl
    mode: 0644
    owner: vault
    group: vault
  tags: config