---
- name: Install ruby
  ansible.builtin.package:
    name: ruby
    state: present
  tags: helper

- name: Add vault agent config
  ansible.builtin.template:
    src: opt/vault/token-helper.rb.j2
    dest: /opt/vault/token-helper.rb
    mode: "0755"
    owner: vault
    group: vault
  tags: helper

- name: Add Vault environment file for bash execution
  ansible.builtin.template:
    src: etc/profile.d/vault.sh.j2
    dest: /etc/profile.d/vault.sh
    mode: "0755"
    owner: vault
    group: vault
  tags: helper

# https://www.hashicorp.com/blog/building-a-vault-token-helper
- name: Add vault token helper pointer
  ansible.builtin.template:
    src: .vault.j2
    dest: /root/.vault
    mode: "0640"
  tags: helper

- name: Add vault token helper pointer for service user specific to app
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: .vault.j2
    dest: ~/.vault
    mode: "0750"
  loop: "{{ app_service_users }}"
  when: app_service_users is defined
  tags: helper
